wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741916757.160836
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.17
      5: 0.15.7
      8:
      - 3
      - 5
